[2025-06-30T21:22:47.057+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-30T21:15:48.004028+00:00 [queued]>
[2025-06-30T21:22:47.083+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-30T21:15:48.004028+00:00 [queued]>
[2025-06-30T21:22:47.084+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-30T21:22:47.124+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-06-30 21:15:48.004028+00:00
[2025-06-30T21:22:47.134+0000] {standard_task_runner.py:60} INFO - Started process 392 to run task
[2025-06-30T21:22:47.164+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-06-30T21:15:48.004028+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp869k6o1b']
[2025-06-30T21:22:47.181+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask carregamento_postgres
[2025-06-30T21:22:47.349+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-06-30T21:15:48.004028+00:00 [running]> on host 91939db6f4b6
[2025-06-30T21:22:47.624+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T21:15:48.004028+00:00' AIRFLOW_CTX_TRY_NUM***ER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T21:15:48.004028+00:00'
[2025-06-30T21:22:48.003+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-06-30T21:22:49.822+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-30T21:22:52.859+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:52.858932Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-30T21:22:52.876+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:52.875516Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-30T21:22:52.897+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:52.897108Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-30T21:22:52.927+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:52.926153Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-30T21:22:52.949+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:52.948378Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-30T21:22:52.979+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:52.978169Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-30T21:22:53.006+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:53.005381Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-30T21:22:53.057+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:53.056927Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-30T21:22:55.705+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:55.704265Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-30T21:22:55.718+0000] {docker.py:429} INFO - [2m2025-06-30T21:22:55.717685Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-30T21:23:00.924+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:00.923632Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-30T21:23:01.023+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:01.022837Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-30T21:23:01.053+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:01.053098Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-30T21:23:01.617+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:01.616007Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-30T21:23:01.618+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:01.617943Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-06-30T21:23:01.619+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:01.618528Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-30T21:23:05.197+0000] {docker.py:429} INFO - Meltano install completed. Executing command: meltano el tap-csv-latest target-postgres
[2025-06-30T21:23:06.719+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:06.718863Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-06-30T21:23:07.598+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:07.596914Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m
[2025-06-30T21:23:08.892+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:08.891139Z[0m [[32m[1minfo     [0m] [1mtap-csv: './meltano/config/tap-csv-latest.json' file not found[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.048+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.047907Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.051+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.050050Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-30T21:23:09.050599Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-30T21:23:09.050993Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.052+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.051641Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.053+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.052499Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.054+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.053202Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.054+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.054003Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.055+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.054762Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.055+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.055248Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.056+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.055734Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.056+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.056461Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.057+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.056977Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 98, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.058+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.057723Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.058+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.058083Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.059+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.058554Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.059+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.058902Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.059+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.059227Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-06-30T21:23:09.059552Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 583, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.060+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.059882Z[0m [[32m[1minfo     [0m] [1m    target = cls(             [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.060+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.060301Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/target_postgres/target.py", line 62, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.061+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.060695Z[0m [[32m[1minfo     [0m] [1m    assert (self.config.get("sqlalchemy_url") is not None) or ([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.061+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.061040Z[0m [[32m[1minfo     [0m] [1mAssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.157+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.156477Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m"tap-csv: './meltano/config/tap-csv-latest.json' file not found"[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m
[2025-06-30T21:23:09.157+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.156863Z[0m [[31m[1merror    [0m] [1mLoading failed                [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'AssertionError: Need either the sqlalchemy_url to be set or host, port, user, password, and dialect+driver to be set'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m
[2025-06-30T21:23:09.158+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.157664Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor and loader failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.158+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.157933Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.158+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.158196Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-30T212307--tap-csv-latest--target-postgres/57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.158+0000] {docker.py:429} INFO - [2m2025-06-30T21:23:09.158450Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5[0m [36mstate_id[0m=[35m2025-06-30T212307--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-06-30T21:23:09.171+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor and loader failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-06-30T212307--tap-csv-latest--target-postgres/57241b5b-b1a6-4a9a-bbb4-e5cc4a5954e5/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-06-30T21:23:10.200+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-30T21:23:10.213+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250630T211548, start_date=20250630T212247, end_date=20250630T212310
[2025-06-30T21:23:10.343+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-06-30T21:23:10.345+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-06-30T21:23:10.346+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-06-30T21:23:10.370+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-06-30T21:23:10.371+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-06-30T21:23:10.372+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-06-30T21:23:10.406+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 392)
[2025-06-30T21:23:10.435+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-30T21:23:10.466+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
