[2025-06-23T23:18:08.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.gerar_config_py manual__2025-06-23T23:17:06.498232+00:00 [queued]>
[2025-06-23T23:18:08.270+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.gerar_config_py manual__2025-06-23T23:17:06.498232+00:00 [queued]>
[2025-06-23T23:18:08.271+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-23T23:18:08.290+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): gerar_config_py> on 2025-06-23 23:17:06.498232+00:00
[2025-06-23T23:18:08.299+0000] {standard_task_runner.py:60} INFO - Started process 189 to run task
[2025-06-23T23:18:08.305+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'gerar_config_py', 'manual__2025-06-23T23:17:06.498232+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpib4qiesk']
[2025-06-23T23:18:08.308+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask gerar_config_py
[2025-06-23T23:18:08.385+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.gerar_config_py manual__2025-06-23T23:17:06.498232+00:00 [running]> on host a06304be4538
[2025-06-23T23:18:08.493+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='gerar_config_py' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T23:17:06.498232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T23:17:06.498232+00:00'
[2025-06-23T23:18:08.673+0000] {docker.py:359} INFO - Starting docker container from image indicium_pipeline-meltano:latest
[2025-06-23T23:18:09.465+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-23T23:18:11.312+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.312131Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-23T23:18:11.328+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.328034Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-23T23:18:11.347+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.346308Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-23T23:18:11.375+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.373625Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-23T23:18:11.412+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.409283Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-23T23:18:11.449+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.448150Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-23T23:18:11.500+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.494725Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-23T23:18:11.540+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:11.539391Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-23T23:18:13.409+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:13.409039Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-23T23:18:13.410+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:13.409819Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-23T23:18:17.838+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:17.837583Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-23T23:18:18.330+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:18.328856Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-23T23:18:18.844+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:18.843556Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-23T23:18:19.019+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:19.018597Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-23T23:18:19.085+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:19.084949Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-06-23T23:18:19.086+0000] {docker.py:429} INFO - [2m2025-06-23T23:18:19.085415Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-23T23:18:20.005+0000] {docker.py:429} INFO - Meltano install completed. Executing command: python3 scripts/generate_csv_config.py
[2025-06-23T23:18:20.039+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/opt/meltano/scripts/generate_csv_config.py", line 17, in <module>
    latest_date_path = max([d for d in csv_base.iterdir() if d.is_dir()], key=os.path.getmtime, default=None)
  File "/opt/meltano/scripts/generate_csv_config.py", line 17, in <listcomp>
    latest_date_path = max([d for d in csv_base.iterdir() if d.is_dir()], key=os.path.getmtime, default=None)
  File "/usr/local/lib/python3.10/pathlib.py", line 1017, in iterdir
[2025-06-23T23:18:20.040+0000] {docker.py:429} INFO - for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/csv/order_details'
[2025-06-23T23:18:20.292+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-23T23:18:20.299+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=gerar_config_py, execution_date=20250623T231706, start_date=20250623T231808, end_date=20250623T231820
[2025-06-23T23:18:20.321+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 45 for task gerar_config_py (Docker container failed: {'StatusCode': 1}; 189)
[2025-06-23T23:18:20.367+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-23T23:18:20.388+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
