[2025-06-23T22:48:22.251+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.gerar_config_py manual__2025-06-23T22:47:06.907656+00:00 [queued]>
[2025-06-23T22:48:22.264+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.gerar_config_py manual__2025-06-23T22:47:06.907656+00:00 [queued]>
[2025-06-23T22:48:22.264+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-23T22:48:22.278+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): gerar_config_py> on 2025-06-23 22:47:06.907656+00:00
[2025-06-23T22:48:22.286+0000] {standard_task_runner.py:60} INFO - Started process 189 to run task
[2025-06-23T22:48:22.291+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'gerar_config_py', 'manual__2025-06-23T22:47:06.907656+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpythf10mw']
[2025-06-23T22:48:22.293+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask gerar_config_py
[2025-06-23T22:48:22.354+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.gerar_config_py manual__2025-06-23T22:47:06.907656+00:00 [running]> on host a06304be4538
[2025-06-23T22:48:22.444+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='gerar_config_py' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T22:47:06.907656+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T22:47:06.907656+00:00'
[2025-06-23T22:48:22.762+0000] {docker.py:359} INFO - Starting docker container from image indicium_pipeline-meltano:latest
[2025-06-23T22:48:23.305+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-23T22:48:25.211+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.210117Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-23T22:48:25.224+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.223520Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-23T22:48:25.242+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.241357Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-23T22:48:25.264+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.263094Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-23T22:48:25.294+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.293811Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-23T22:48:25.332+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.331108Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-23T22:48:25.373+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.372605Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-23T22:48:25.417+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:25.416012Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-23T22:48:27.998+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:27.997824Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-23T22:48:28.161+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:28.160653Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-23T22:48:35.186+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:35.185124Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-23T22:48:35.192+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:35.190802Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-23T22:48:35.704+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:35.703085Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-23T22:48:36.125+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:36.124422Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-23T22:48:36.278+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:36.277472Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-06-23T22:48:36.279+0000] {docker.py:429} INFO - [2m2025-06-23T22:48:36.278212Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-23T22:48:37.428+0000] {docker.py:429} INFO - Meltano install completed. Executing command: python3 scripts/generate_csv_config.py
[2025-06-23T22:48:37.543+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/opt/meltano/scripts/generate_csv_config.py", line 17, in <module>
    latest_date_path = max([d for d in csv_base.iterdir() if d.is_dir()], key=os.path.getmtime, default=None)
  File "/opt/meltano/scripts/generate_csv_config.py", line 17, in <listcomp>
[2025-06-23T22:48:37.544+0000] {docker.py:429} INFO - latest_date_path = max([d for d in csv_base.iterdir() if d.is_dir()], key=os.path.getmtime, default=None)
  File "/usr/local/lib/python3.10/pathlib.py", line 1017, in iterdir
[2025-06-23T22:48:37.546+0000] {docker.py:429} INFO - for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/csv/order_details'
[2025-06-23T22:48:37.986+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-23T22:48:38.005+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=gerar_config_py, execution_date=20250623T224706, start_date=20250623T224822, end_date=20250623T224837
[2025-06-23T22:48:38.079+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task gerar_config_py (Docker container failed: {'StatusCode': 1}; 189)
[2025-06-23T22:48:38.129+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-23T22:48:38.236+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
