[2025-06-25T21:11:12.016+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.extração_postgres manual__2025-06-25T21:11:10.445750+00:00 [queued]>
[2025-06-25T21:11:12.042+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.extração_postgres manual__2025-06-25T21:11:10.445750+00:00 [queued]>
[2025-06-25T21:11:12.042+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-25T21:11:12.092+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): extração_postgres> on 2025-06-25 21:11:10.445750+00:00
[2025-06-25T21:11:12.128+0000] {standard_task_runner.py:60} INFO - Started process 189 to run task
[2025-06-25T21:11:12.184+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'extração_postgres', 'manual__2025-06-25T21:11:10.445750+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpp6w03n9b']
[2025-06-25T21:11:12.214+0000] {standard_task_runner.py:88} INFO - Job 191: Subtask extração_postgres
[2025-06-25T21:11:12.562+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.extração_postgres manual__2025-06-25T21:11:10.445750+00:00 [running]> on host 6afc1f3750fb
[2025-06-25T21:11:12.734+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='extração_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T21:11:10.445750+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T21:11:10.445750+00:00'
[2025-06-25T21:11:13.429+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-06-25T21:11:13.451+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 364, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.10/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.10/site-packages/docker/api/container.py", line 455, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/home/airflow/.local/lib/python3.10/site-packages/docker/api/client.py", line 293, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
[2025-06-25T21:11:13.491+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=extração_postgres, execution_date=20250625T211110, start_date=20250625T211112, end_date=20250625T211113
[2025-06-25T21:11:13.531+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 191 for task extração_postgres (Object of type PosixPath is not JSON serializable; 189)
[2025-06-25T21:11:13.574+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-25T21:11:13.612+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
