[2025-06-25T21:09:36.027+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-25T21:01:24.669781+00:00 [queued]>
[2025-06-25T21:09:36.040+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-25T21:01:24.669781+00:00 [queued]>
[2025-06-25T21:09:36.040+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-25T21:09:36.057+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-06-25 21:01:24.669781+00:00
[2025-06-25T21:09:36.073+0000] {standard_task_runner.py:60} INFO - Started process 172 to run task
[2025-06-25T21:09:36.080+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-06-25T21:01:24.669781+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjjifsl49']
[2025-06-25T21:09:36.085+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask carregamento_postgres
[2025-06-25T21:09:36.177+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-06-25T21:01:24.669781+00:00 [running]> on host 6afc1f3750fb
[2025-06-25T21:09:36.358+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T21:01:24.669781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T21:01:24.669781+00:00'
[2025-06-25T21:09:36.849+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-06-25T21:09:36.851+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 391, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.10/site-packages/docker/api/container.py", line 439, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.10/site-packages/docker/api/container.py", line 455, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/home/airflow/.local/lib/python3.10/site-packages/docker/api/client.py", line 293, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
[2025-06-25T21:09:36.871+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250625T210124, start_date=20250625T210936, end_date=20250625T210936
[2025-06-25T21:09:36.897+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task carregamento_postgres (Object of type PosixPath is not JSON serializable; 172)
[2025-06-25T21:09:36.922+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-25T21:09:36.939+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
