[2025-07-09T22:00:55.121+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T21:54:52.345768+00:00 [queued]>
[2025-07-09T22:00:55.134+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T21:54:52.345768+00:00 [queued]>
[2025-07-09T22:00:55.135+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-09T22:00:55.155+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-09 21:54:52.345768+00:00
[2025-07-09T22:00:55.163+0000] {standard_task_runner.py:60} INFO - Started process 170 to run task
[2025-07-09T22:00:55.167+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-09T21:54:52.345768+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmpqfael1rl']
[2025-07-09T22:00:55.171+0000] {standard_task_runner.py:88} INFO - Job 126: Subtask carregamento_postgres
[2025-07-09T22:00:55.259+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-09T21:54:52.345768+00:00 [running]> on host ae92b363b970
[2025-07-09T22:00:55.413+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T21:54:52.345768+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T21:54:52.345768+00:00'
[2025-07-09T22:00:56.067+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-09T22:00:56.984+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-09T22:01:01.112+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.111892Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-09T22:01:01.132+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.132080Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-09T22:01:01.165+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.164047Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-09T22:01:01.202+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.201363Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-09T22:01:01.250+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.249584Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-09T22:01:01.325+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.324385Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-09T22:01:01.380+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.379469Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-09T22:01:01.434+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:01.432831Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-09T22:01:03.587+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:03.585870Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-09T22:01:03.664+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:03.664028Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-09T22:01:07.284+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:07.282579Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-09T22:01:07.332+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:07.331364Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-09T22:01:07.516+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:07.515062Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-09T22:01:09.069+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:09.068648Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-09T22:01:09.150+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:09.149222Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-09T22:01:09.151+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:09.150050Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-09T22:01:10.181+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c meltano config tap-csv-latest set csv_files_definition /opt/meltano/config/tap-csv-latest.json && meltano el tap-csv-latest target-postgres
[2025-07-09T22:01:12.485+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:12.484438Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-07-09T22:01:12.734+0000] {docker.py:429} INFO - Extractor 'tap-csv-latest' setting 'csv_files_definition' was set in `meltano.yml`: '/opt/meltano/config/tap-csv-latest.json'
[2025-07-09T22:01:15.460+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:15.459103Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-09T22:01:16.518+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:16.517373Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m
[2025-07-09T22:01:17.682+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.681489Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'order_details'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:17.683+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.682326Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:17.878+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.878169Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:17.881+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.880333Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:17.882+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.880735Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:17.883+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.881114Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:17.883+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:17.881537Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.121+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.120307Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.121+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.120907Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.122+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.121491Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.122+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.121906Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.127+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.125967Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.128+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.126951Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.128+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.127742Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.129+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.128712Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.130+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.129536Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.130+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.130069Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.131+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.131014Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.131+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.131382Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.132+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.131770Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.134+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.132970Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.135+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.134520Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.136+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.135304Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.136+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.135782Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.136+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.136286Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.137+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.136763Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.137+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.137116Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.138+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.137499Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.138+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.137820Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.139+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.138228Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.139+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.138783Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.139+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.139298Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.140+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.139652Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.140+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.140012Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.140+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.140391Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.141+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.140724Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.141+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.141223Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.142+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.142049Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.142+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.142401Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 96, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.143+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.142739Z[0m [[32m[1minfo     [0m] [1m    attempts = conninfo_attempts(params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.143+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.143077Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/_conninfo_attempts.py", line 53, in conninfo_attempts[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T22:01:18.143466Z[0m [[32m[1minfo     [0m] [1m    raise e.OperationalError(str(last_exc))[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.144+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.143827Z[0m [[32m[1minfo     [0m] [1mpsycopg.OperationalError: [Errno -2] Name or service not known[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.144+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.144180Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.145+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.144648Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.145+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.144992Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.146+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.145422Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.147+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.145765Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.147+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.146103Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.147+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.146503Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.148+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.147121Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.148+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.147584Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T22:01:18.147952Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.149+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.148343Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 98, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.150+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.148665Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.150+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.149061Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.150+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.149889Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.151+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.150330Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.152+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.151552Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.153+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.152168Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 588, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.153+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.152879Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.154+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.153463Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 775, in listen[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.154+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.153828Z[0m [[32m[1minfo     [0m] [1m    counter = self.process_lines(file_input)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.154+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.154222Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 801, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.155+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.154597Z[0m [[32m[1minfo     [0m] [1m    return self.message_reader.process_lines([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.155+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.154967Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/singerlib/encoding/base.py", line 70, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.155+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.155294Z[0m [[32m[1minfo     [0m] [1m    callback(line_dict)       [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.156+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.155615Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 403, in _process_schema_message[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T22:01:18.155916Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.156+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.156319Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 817, in get_sink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.157+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.156699Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.157+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.157060Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 751, in add_sqlsink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.158+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.157502Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.158+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.157828Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/target_postgres/sinks.py", line 58, in setup[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.158+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.158213Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema(self.schema_name)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.159+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.158612Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1367, in prepare_schema[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.160+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.159408Z[0m [[32m[1minfo     [0m] [1m    if not self.schema_exists(schema_name):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.160+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.159833Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1200, in schema_exists[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.161+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.160240Z[0m [[32m[1minfo     [0m] [1m    schemas = set(sa.inspect(self._engine).get_schema_names())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.161+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.160650Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 140, in inspect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.161+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.161018Z[0m [[32m[1minfo     [0m] [1m    ret = reg(subject)        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.162+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.161414Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 313, in _engine_insp[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.162+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.161819Z[0m [[32m[1minfo     [0m] [1m    return Inspector._construct(Inspector._init_engine, bind)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.162+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.162187Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 246, in _construct[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.163+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.162569Z[0m [[32m[1minfo     [0m] [1m    init(self, bind)          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.163+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.162890Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 257, in _init_engine[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.163+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.163462Z[0m [[32m[1minfo     [0m] [1m    engine.connect().close()  [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.164+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.163908Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.165+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.164372Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.165+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.164892Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.165+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.165337Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.166+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.165882Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.169+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.166567Z[0m [[32m[1minfo     [0m] [1m    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.171+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.167269Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.174+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.171889Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.174+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.174023Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.175+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.174529Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.175+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.174882Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.176+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.175221Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.176+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.175558Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.177+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.175864Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.177+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.176159Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.178+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.176476Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.178+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.176820Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.179+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.177239Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.179+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.177619Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.180+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.177981Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.180+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.178395Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.180+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.178808Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.181+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.179153Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.181+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.179630Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.182+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.180226Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.182+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.180611Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.183+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.180961Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.183+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.181472Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.184+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.182050Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.184+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.182623Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.184+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.183043Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.185+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.183819Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.185+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.184277Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.186+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.184753Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.186+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.185256Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.186+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.185706Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.187+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.186258Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 96, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.187+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.186775Z[0m [[32m[1minfo     [0m] [1m    attempts = conninfo_attempts(params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.187+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.187217Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/_conninfo_attempts.py", line 53, in conninfo_attempts[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.188+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.187891Z[0m [[32m[1minfo     [0m] [1m    raise e.OperationalError(str(last_exc))[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.190+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.188377Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.OperationalError: (psycopg.OperationalError) [Errno -2] Name or service not known[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.190+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.190180Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/20/e3q8)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35mb396ab24-2d19-46d5-ad18-000019810e37[0m [36mstate_id[0m=[35m2025-07-09T220115--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T22:01:18.897+0000] {docker.py:429} INFO - [2m2025-07-09T22:01:18.318606Z[0m [[31m[1merror    [0m] [1m                              [0m
[31m╭─[0m[31m────────────────────[0m[31m [0m[1;31mTraceback [0m[1;2;31m(most recent call last)[0m[31m [0m[31m─────────────────────[0m[31m─╮[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1moutput_logger.py[0m:217  [31m│[0m
[31m│[0m in redirect_logging                                                          [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m214 [0m[2m│   │   │   [0m*ignore_errors,                                            [31m│[0m
[31m│[0m   [2m215 [0m[2m│   │   [0m)                                                              [31m│[0m
[31m│[0m   [2m216 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m [31m❱ [0m217 [2m│   │   │   [0m[94myield[0m                                                      [31m│[0m
[31m│[0m   [2m218 [0m[2m│   │   [0m[94mexcept[0m ignored_errors:                                         [31m│[0m
[31m│[0m   [2m219 [0m[2m│   │   │   [0m[94mraise[0m                                                      [31m│[0m
[31m│[0m   [2m220 [0m[2m│   │   [0m[94mexcept[0m RunnerError [94mas[0m err:                                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:475 in _redirect_output [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m472 [0m[2m│   [0m[94mwith[0m meltano_stdout.redirect_logging(ignore_errors=(CliError,)):   [31m│[0m
[31m│[0m   [2m473 [0m[2m│   │   [0m[94masync[0m [94mwith[0m meltano_stdout.redirect_stdout(), meltano_stderr.re [31m│[0m
[31m│[0m   [2m474 [0m[2m│   │   │   [0m[94mtry[0m:                                                       [31m│[0m
[31m│[0m [31m❱ [0m475 [2m│   │   │   │   [0m[94myield[0m                                                  [31m│[0m
[31m│[0m   [2m476 [0m[2m│   │   │   [0m[94mexcept[0m CliError [94mas[0m err:                                    [31m│[0m
[31m│[0m   [2m477 [0m[2m│   │   │   │   [0merr.print()                                            [31m│[0m
[31m│[0m   [2m478 [0m[2m│   │   │   │   [0m[94mraise[0m                                                  [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:508 in _run_elt         [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m505 [0m[2m│   │   │   [0m[94mif[0m elt_context.only_transform:                             [31m│[0m
[31m│[0m   [2m506 [0m[2m│   │   │   │   [0mlog.info([33m"[0m[33mExtract & load skipped.[0m[33m"[0m)                    [31m│[0m
[31m│[0m   [2m507 [0m[2m│   │   │   [0m[94melse[0m:                                                      [31m│[0m
[31m│[0m [31m❱ [0m508 [2m│   │   │   │   [0m[94mawait[0m _run_extract_load(log, elt_context, output_logge [31m│[0m
[31m│[0m   [2m509 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m510 [0m[2m│   │   │   [0m[94mif[0m elt_context.transformer:                                [31m│[0m
[31m│[0m   [2m511 [0m[2m│   │   │   │   [0mlog.warning(                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:581 in                  [31m│[0m
[31m│[0m _run_extract_load                                                            [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m578 [0m[2m│   │   │   [0m[94mwith[0m loader_log.line_writer() [94mas[0m loader_log_writer:        [31m│[0m
[31m│[0m   [2m579 [0m[2m│   │   │   │   [0m[94mwith[0m extractor_out_writer_ctxmgr() [94mas[0m extractor_out_wr [31m│[0m
[31m│[0m   [2m580 [0m[2m│   │   │   │   │   [0m[94mwith[0m loader_out_writer_ctxmgr() [94mas[0m loader_out_writ [31m│[0m
[31m│[0m [31m❱ [0m581 [2m│   │   │   │   │   │   [0m[94mawait[0m singer_runner.run(                       [31m│[0m
[31m│[0m   [2m582 [0m[2m│   │   │   │   │   │   │   [0m**kwargs,                                  [31m│[0m
[31m│[0m   [2m583 [0m[2m│   │   │   │   │   │   │   [0mextractor_log=extractor_log_writer,        [31m│[0m
[31m│[0m   [2m584 [0m[2m│   │   │   │   │   │   │   [0mloader_log=loader_log_writer,              [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:229 in run   [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m226 [0m[2m│   │   │   [0mtap.prepared([96mself[0m.context.session),                        [31m│[0m
[31m│[0m   [2m227 [0m[2m│   │   │   [0mtarget.prepared([96mself[0m.context.session),                     [31m│[0m
[31m│[0m   [2m228 [0m[2m│   │   [0m):                                                             [31m│[0m
[31m│[0m [31m❱ [0m229 [2m│   │   │   [0m[94mawait[0m [96mself[0m.invoke(  [2m# noqa: RET503[0m                         [31m│[0m
[31m│[0m   [2m230 [0m[2m│   │   │   │   [0mtap,                                                   [31m│[0m
[31m│[0m   [2m231 [0m[2m│   │   │   │   [0mtarget,                                                [31m│[0m
[31m│[0m   [2m232 [0m[2m│   │   │   │   [0mextractor_log=extractor_log,                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:148 in       [31m│[0m
[31m│[0m invoke                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m145 [0m[2m│   │   │   │   │   [0m)                                                  [31m│[0m
[31m│[0m   [2m146 [0m[2m│   │   │   │   [0m                                                       [31m│[0m
[31m│[0m   [2m147 [0m[2m│   │   │   │   [0mfailed_future = output_futures_failed.pop()            [31m│[0m
[31m│[0m [31m❱ [0m148 [2m│   │   │   │   [0m[94mraise[0m failed_future.exception()                        [31m│[0m
[31m│[0m   [2m149 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m150 [0m[2m│   │   │   [0m[2m# If all of the output handlers completed without raising [0m [31m│[0m
[31m│[0m   [2m151 [0m[2m│   │   │   [0m[2m# exception, we still need to wait for the tap or target t[0m [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:305 in       [31m│[0m
[31m│[0m capture_subprocess_output                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m302 [0m[2m│   │   │   [0m[94mcontinue[0m                                                   [31m│[0m
[31m│[0m   [2m303 [0m[2m│   │   [0m                                                               [31m│[0m
[31m│[0m   [2m304 [0m[2m│   │   [0m[94mfor[0m writer [95min[0m line_writers:                                    [31m│[0m
[31m│[0m [31m❱ [0m305 [2m│   │   │   [0m[94mif[0m [95mnot[0m [94mawait[0m _write_line_writer(writer, line):             [31m│[0m
[31m│[0m   [2m306 [0m[2m│   │   │   │   [0m[2m# If the destination stream is closed, we can stop cap[0m [31m│[0m
[31m│[0m   [2m307 [0m[2m│   │   │   │   [0m[94mreturn[0m                                                 [31m│[0m
[31m│[0m   [2m308 [0m                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:273 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m   [2m271 [0m[2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m [31m❱ [0m273 [2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m   [2m275 [0m[2m│   [0m[94melse[0m:                                                              [31m│[0m
[31m│[0m   [2m276 [0m[2m│   │   [0mwriter.writeline(line.decode(errors=[33m"[0m[33mreplace[0m[33m"[0m))                [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:359 in wait_closed               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m356 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.is_closing()                            [31m│[0m
[31m│[0m   [2m357 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m358 [0m[2m│   [0m[94masync[0m [94mdef[0m[90m [0m[92mwait_closed[0m([96mself[0m):                                       [31m│[0m
[31m│[0m [31m❱ [0m359 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._get_close_waiter([96mself[0m)                   [31m│[0m
[31m│[0m   [2m360 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m361 [0m[2m│   [0m[94mdef[0m[90m [0m[92mget_extra_info[0m([96mself[0m, name, default=[94mNone[0m):                      [31m│[0m
[31m│[0m   [2m362 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.get_extra_info(name, default)           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:271 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m268 [0m[2m│   [0m[94mif[0m [96misinstance[0m(writer, asyncio.StreamWriter):                       [31m│[0m
[31m│[0m   [2m269 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m [31m❱ [0m271 [2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m   [2m273 [0m[2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:387 in drain                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m384 [0m[2m│   │   │   [0m[2m# in a loop would never call connection_lost(), so it[0m      [31m│[0m
[31m│[0m   [2m385 [0m[2m│   │   │   [0m[2m# would not see an error when the socket is closed.[0m        [31m│[0m
[31m│[0m   [2m386 [0m[2m│   │   │   [0m[94mawait[0m sleep([94m0[0m)                                             [31m│[0m
[31m│[0m [31m❱ [0m387 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._drain_helper()                           [31m│[0m
[31m│[0m   [2m388 [0m                                                                       [31m│[0m
[31m│[0m   [2m389 [0m                                                                       [31m│[0m
[31m│[0m   [2m390 [0m[94mclass[0m[90m [0m[4;92mStreamReader[0m:                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:197 in _drain_helper             [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m194 [0m[2m│   │   [0m[94massert[0m waiter [95mis[0m [94mNone[0m [95mor[0m waiter.cancelled()                    [31m│[0m
[31m│[0m   [2m195 [0m[2m│   │   [0mwaiter = [96mself[0m._loop.create_future()                            [31m│[0m
[31m│[0m   [2m196 [0m[2m│   │   [0m[96mself[0m._drain_waiter = waiter                                    [31m│[0m
[31m│[0m [31m❱ [0m197 [2m│   │   [0m[94mawait[0m waiter                                                   [31m│[0m
[31m│[0m   [2m198 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m199 [0m[2m│   [0m[94mdef[0m[90m [0m[92m_get_close_waiter[0m([96mself[0m, stream):                               [31m│[0m
[31m│[0m   [2m200 [0m[2m│   │   [0m[94mraise[0m [96mNotImplementedError[0m                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────╯[0m
[1;91mBrokenPipeError[0m
[2025-07-09T22:01:18.913+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
[2025-07-09T22:01:20.202+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-09T22:01:20.212+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250709T215452, start_date=20250709T220055, end_date=20250709T220120
[2025-07-09T22:01:20.266+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-09T22:01:20.266+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-09T22:01:20.267+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-09T22:01:20.280+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-09T22:01:20.280+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-09T22:01:20.281+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-09T22:01:20.303+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 126 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 170)
[2025-07-09T22:01:20.348+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-09T22:01:20.402+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
