[2025-06-23T22:52:12.140+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.gerar_config_py manual__2025-06-23T22:51:28.664619+00:00 [queued]>
[2025-06-23T22:52:12.149+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.gerar_config_py manual__2025-06-23T22:51:28.664619+00:00 [queued]>
[2025-06-23T22:52:12.150+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-23T22:52:12.163+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): gerar_config_py> on 2025-06-23 22:51:28.664619+00:00
[2025-06-23T22:52:12.168+0000] {standard_task_runner.py:60} INFO - Started process 235 to run task
[2025-06-23T22:52:12.173+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'gerar_config_py', 'manual__2025-06-23T22:51:28.664619+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw6hbia_j']
[2025-06-23T22:52:12.175+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask gerar_config_py
[2025-06-23T22:52:12.229+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.gerar_config_py manual__2025-06-23T22:51:28.664619+00:00 [running]> on host a06304be4538
[2025-06-23T22:52:12.306+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='gerar_config_py' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T22:51:28.664619+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T22:51:28.664619+00:00'
[2025-06-23T22:52:12.440+0000] {docker.py:359} INFO - Starting docker container from image indicium_pipeline-meltano:latest
[2025-06-23T22:52:12.858+0000] {docker.py:429} INFO - Running meltano install...
[2025-06-23T22:52:14.447+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.446548Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-06-23T22:52:14.465+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.464635Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-06-23T22:52:14.487+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.486704Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-06-23T22:52:14.515+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.513293Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-06-23T22:52:14.535+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.534842Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-06-23T22:52:14.571+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.570637Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-06-23T22:52:14.618+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.617119Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-06-23T22:52:14.677+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:14.674271Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-06-23T22:52:16.371+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:16.370731Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-06-23T22:52:16.504+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:16.504108Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-06-23T22:52:21.346+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:21.345262Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-06-23T22:52:21.362+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:21.361442Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-06-23T22:52:22.315+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:22.315186Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-06-23T22:52:22.645+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:22.644435Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-06-23T22:52:22.645+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:22.644934Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-06-23T22:52:22.646+0000] {docker.py:429} INFO - [2m2025-06-23T22:52:22.645184Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-06-23T22:52:23.561+0000] {docker.py:429} INFO - Meltano install completed. Executing command: python3 scripts/generate_csv_config.py
[2025-06-23T22:52:23.597+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/opt/meltano/scripts/generate_csv_config.py", line 17, in <module>
    latest_date_path = max([d for d in csv_base.iterdir() if d.is_dir()], key=os.path.getmtime, default=None)
  File "/opt/meltano/scripts/generate_csv_config.py", line 17, in <listcomp>
    latest_date_path = max([d for d in csv_base.iterdir() if d.is_dir()], key=os.path.getmtime, default=None)
  File "/usr/local/lib/python3.10/pathlib.py", line 1017, in iterdir
[2025-06-23T22:52:23.599+0000] {docker.py:429} INFO - for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/csv/order_details'
[2025-06-23T22:52:23.795+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-06-23T22:52:23.802+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=gerar_config_py, execution_date=20250623T225128, start_date=20250623T225212, end_date=20250623T225223
[2025-06-23T22:52:23.818+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task gerar_config_py (Docker container failed: {'StatusCode': 1}; 235)
[2025-06-23T22:52:23.848+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-23T22:52:23.874+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
