[2025-06-26T17:13:05.764+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-26T17:12:00.298704+00:00 [queued]>
[2025-06-26T17:13:05.772+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-06-26T17:12:00.298704+00:00 [queued]>
[2025-06-26T17:13:05.773+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-26T17:13:05.789+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-06-26 17:12:00.298704+00:00
[2025-06-26T17:13:05.795+0000] {standard_task_runner.py:60} INFO - Started process 340 to run task
[2025-06-26T17:13:05.798+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-06-26T17:12:00.298704+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmperx4pb8n']
[2025-06-26T17:13:05.801+0000] {standard_task_runner.py:88} INFO - Job 308: Subtask carregamento_postgres
[2025-06-26T17:13:05.849+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-06-26T17:12:00.298704+00:00 [running]> on host 6afc1f3750fb
[2025-06-26T17:13:05.892+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'carregamento_postgres', field 'command'. Template: ['bash', '/opt/***/dags/scripts/load_meltano.sh', '{{ task_instance.xcom_pull(task_ids=\'gerar_config_csv_dinamica\') | tojson | replace(\'"\', \'\\"\') }}', '{{ task_instance.xcom_pull(task_ids=\'gerar_config_target_postgres_dinamica\') | tojson | replace(\'"\', \'\\"\') }}']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 184, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 184, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/scripts/load_meltano.sh
[2025-06-26T17:13:05.897+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 184, in render_template
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 184, in <listcomp>
    return [self.render_template(element, context, jinja_env, oids) for element in value]
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/scripts/load_meltano.sh
[2025-06-26T17:13:05.910+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250626T171200, start_date=20250626T171305, end_date=20250626T171305
[2025-06-26T17:13:05.928+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 308 for task carregamento_postgres (/opt/airflow/dags/scripts/load_meltano.sh; 340)
[2025-06-26T17:13:05.974+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-26T17:13:05.993+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
