[2025-07-01T13:51:45.032+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-01T13:45:28.592454+00:00 [queued]>
[2025-07-01T13:51:45.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-01T13:45:28.592454+00:00 [queued]>
[2025-07-01T13:51:45.044+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-01T13:51:45.059+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-01 13:45:28.592454+00:00
[2025-07-01T13:51:45.067+0000] {standard_task_runner.py:60} INFO - Started process 170 to run task
[2025-07-01T13:51:45.072+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-01T13:45:28.592454+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu6n3ihj2']
[2025-07-01T13:51:45.075+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask carregamento_postgres
[2025-07-01T13:51:45.235+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-01T13:45:28.592454+00:00 [running]> on host 106da672717e
[2025-07-01T13:51:45.862+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T13:45:28.592454+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-01T13:45:28.592454+00:00'
[2025-07-01T13:51:46.080+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-01T13:51:46.917+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-01T13:51:50.754+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.753548Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-01T13:51:50.770+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.769629Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-01T13:51:50.798+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.797123Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-01T13:51:50.831+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.829847Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-01T13:51:50.864+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.863873Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-01T13:51:50.913+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.912308Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-01T13:51:50.968+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:50.967509Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-01T13:51:51.025+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:51.024266Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-01T13:51:53.533+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:53.532707Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-01T13:51:53.666+0000] {docker.py:429} INFO - [2m2025-07-01T13:51:53.665104Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-01T13:52:02.429+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:02.427294Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-01T13:52:02.762+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:02.761597Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-01T13:52:10.529+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:10.527684Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-01T13:52:10.676+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:10.675061Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-01T13:52:03.272+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:03.269780Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2m2025-07-01T13:52:03.270884Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-01T13:52:04.429+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c echo '--- Conte√∫do de MELTANO_TAP_CSV_LATEST_FILES ---' && echo $MELTANO_TAP_CSV_LATEST_FILES && echo '--- Fim do Conte√∫do ---' && meltano el tap-csv-latest target-postgres
[2025-07-01T13:52:04.593+0000] {docker.py:429} INFO - --- Conte√∫do de MELTANO_TAP_CSV_LATEST_FILES ---
[2025-07-01T13:52:04.603+0000] {docker.py:429} INFO - {"files": [{"entity": "order_details", "path": "/opt/output_data/csv/order_details/2025-07-01/file.csv", "keys": ["order_id", "product_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-categories", "path": "/opt/output_data/postgres/public-categories/2025-07-01/file.csv", "keys": ["category_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-products", "path": "/opt/output_data/postgres/public-products/2025-07-01/file.csv", "keys": ["product_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-suppliers", "path": "/opt/output_data/postgres/public-suppliers/2025-07-01/file.csv", "keys": ["supplier_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-orders", "path": "/opt/output_data/postgres/public-orders/2025-07-01/file.csv", "keys": ["order_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-customers", "path": "/opt/output_data/postgres/public-customers/2025-07-01/file.csv", "keys": ["customer_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-employees", "path": "/opt/output_data/postgres/public-employees/2025-07-01/file.csv", "keys": ["employee_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-employee_territories", "path": "/opt/output_data/postgres/public-employee_territories/2025-07-01/file.csv", "keys": ["employee_id", "territory_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-territories", "path": "/opt/output_data/postgres/public-territories/2025-07-01/file.csv", "keys": ["territory_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-region", "path": "/opt/output_data/postgres/public-region/2025-07-01/file.csv", "keys": ["region_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-shippers", "path": "/opt/output_data/postgres/public-shippers/2025-07-01/file.csv", "keys": ["shipper_id"], "delimiter": ",", "encoding": "utf-8"}, {"entity": "public-us_states", "path": "/opt/output_data/postgres/public-us_states/2025-07-01/file.csv", "keys": ["state_id"], "delimiter": ",", "encoding": "utf-8"}]}
--- Fim do Conte√∫do ---
[2025-07-01T13:52:07.354+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:07.354057Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-01T13:52:08.303+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:08.301787Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m
[2025-07-01T13:52:09.158+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.157863Z[0m [[32m[1minfo     [0m] [1mNo CSV file definitions found.[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.396+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.395206Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.397+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.396919Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-01T13:52:09.397291Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.398+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.397563Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.398+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.397829Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.398+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.398207Z[0m [[32m[1minfo     [0m] [1mThe `dialect+driver` configuration option is deprecated. Please set it to `postgresql+psycopg`, as this will be the hard-coded value in the future.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.399+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.398519Z[0m [[32m[1minfo     [0m] [1mReader 'target-postgres' completed processing 0 lines of input (0 schemas, 0 records, 0 batch manifests, 0 state messages, 0 activate version messages).[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.506+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.505551Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'No CSV file definitions found.'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m
[2025-07-01T13:52:09.507+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.506601Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.507+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.507101Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.508+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.507454Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-01T135207--tap-csv-latest--target-postgres/5cff5e6a-ee00-4e8c-9e43-d268c0b970d3/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.508+0000] {docker.py:429} INFO - [2m2025-07-01T13:52:09.507850Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m5cff5e6a-ee00-4e8c-9e43-d268c0b970d3[0m [36mstate_id[0m=[35m2025-07-01T135207--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T13:52:09.525+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-01T135207--tap-csv-latest--target-postgres/5cff5e6a-ee00-4e8c-9e43-d268c0b970d3/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-07-01T13:52:11.178+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T13:52:11.187+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250701T134528, start_date=20250701T135145, end_date=20250701T135211
[2025-07-01T13:52:11.248+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-01T13:52:11.250+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-01T13:52:11.251+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-01T13:52:11.264+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-01T13:52:11.265+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-01T13:52:11.265+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-01T13:52:11.296+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 170)
[2025-07-01T13:52:11.345+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-01T13:52:11.394+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
